---
server:
  port: 8080


spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/emailExpress
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

